<?php

namespace DialogContactForm\Fields;

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Hidden extends Text {

	/**
	 * Metabox fields
	 *
	 * @var array
	 */
	protected $metabox_fields = array(
		'field_type',
		'field_title',
		'field_id',
		'field_value',
	);

	/**
	 * Field type
	 *
	 * @var string
	 */
	protected $type = 'hidden';

	public function render( $field = array() ) {
		return parent::render( $field ); // TODO: Change the autogenerated stub
	}
}